# Generated by Django 4.1.13 on 2024-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="chat_history",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
    ]
