# Generated by Django 5.1 on 2024-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_chatsession_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
