# Generated by Django 5.1.3 on 2024-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_chatsession_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_used_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
