# Generated by Django 5.1.3 on 2024-12-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_chatsession_last_used_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="last_used_at",
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
